/*
 * This file is generated by jOOQ.
*/
package com.yangli907.phome.model;


import com.yangli907.phome.model.tables.Photographer;
import com.yangli907.phome.model.tables.records.PhotographerRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>phollow</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PhotographerRecord, Integer> IDENTITY_PHOTOGRAPHER = Identities0.IDENTITY_PHOTOGRAPHER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PhotographerRecord> KEY_PHOTOGRAPHER_PRIMARY = UniqueKeys0.KEY_PHOTOGRAPHER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<PhotographerRecord, Integer> IDENTITY_PHOTOGRAPHER = createIdentity(Photographer.PHOTOGRAPHER, Photographer.PHOTOGRAPHER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<PhotographerRecord> KEY_PHOTOGRAPHER_PRIMARY = createUniqueKey(Photographer.PHOTOGRAPHER, "KEY_photographer_PRIMARY", Photographer.PHOTOGRAPHER.ID);
    }
}
