/*
 * This file is generated by jOOQ.
*/
package com.yangli907.phome.model;


import com.yangli907.phome.model.tables.Photographer;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Phollow extends SchemaImpl {

    private static final long serialVersionUID = 689773586;

    /**
     * The reference instance of <code>phollow</code>
     */
    public static final Phollow PHOLLOW = new Phollow();

    /**
     * The table <code>phollow.photographer</code>.
     */
    public final Photographer PHOTOGRAPHER = com.yangli907.phome.model.tables.Photographer.PHOTOGRAPHER;

    /**
     * No further instances allowed
     */
    private Phollow() {
        super("phollow", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Photographer.PHOTOGRAPHER);
    }
}
