/*
 * This file is generated by jOOQ.
*/
package com.yangli907.phome.model;


import com.yangli907.phome.model.tables.Photographer;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in phollow
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>phollow.photographer</code>.
     */
    public static final Photographer PHOTOGRAPHER = com.yangli907.phome.model.tables.Photographer.PHOTOGRAPHER;
}
